### ISSUE TITLE
Oneshot option for "run" backend command

### ISSUE THREAD

**Issue by kodiak77** [chimera-linux/turnstile#12]
Hi, I have been trying to write turnstile backend for 66 user service manager for Obarun linux. The user service manager in 66 is managed by the rest of the 66 service hierarchy and is not meant to be run from another process like turnstile (though, it is technically possible). Instead, `66-all up` is used to start the user service manager and `66-all down` to stop it.

I made it work by writing an infinite loop at the end of "run" action, but this doesn't seem to be the most elegant solution. Also, the sleep command which I run in the loop, cannot be interrupted using SIGTERM trivially, which also makes stopping the service manager more difficult.

I am curious if there is any existing or planned way for the "run" action to be a oneshot?

**Comment by q66** [comment]
no, this is not supported by design as turnstile is required to be able to supervise the user service manager

**Comment by Nanderty** [comment]
I would kindly request to add support to this: executing a oneshot on first login and another on last logout.
This oneshot should (like the longrun now) be the same script both times and  be passed the "run" and "stop" args.
The oneshot would need to be ran as root.
This would allow all users of s6/s6-rc and probably 66 to have their user supervision tree supervised and configured by the system supervision tree. Thus limiting the usage of turnstile only for tracking logins/logouts and nothing more, arguably being more elegant for some configurations and giving the system adminitrator/distribution maintainer more freedom.
Would it be possible to add this functionallity?
