### ISSUE TITLE
Cannot figure out D-Bus session bus management

### ISSUE THREAD

**Issue by 62832** [chimera-linux/turnstile#13]
I've been trying for a while now to put together a user service for Dinit running under Turnstile with which to spawn a user session of D-Bus without needing to manually define and export `DBUS_SESSION_BUS_ADDRESS` myself, however it seems like either Turnstile's functionality for this isn't working right or I'm simply looking in the wrong place for it — running `echo $DBUS_SESSION_BUS_ADDRESS` without the existing service running and setting the variable manually yields an empty output.

I am currently using the Artix-maintained packages of `turnstile`, `turnstile-dinit` and `pambase-turnstile`, with the `export_dbus_address = yes` config option.

**Comment by nekopsykose** [comment]
artix has the latest version (0.1.8) which had some bugs (with dummy backend especially, but iirc it should work with dinit..) which prevented that from working

you should check master anyway

**Comment by capezotte** [comment]
Guess this can be closed, since Artix now has a distribution tested and approved `dbus-user-dinit` package (and it works for me).
