### ISSUE TITLE
export variables

### ISSUE THREAD

**Issue by dkwo** [chimera-linux/turnstile#14]
Is there a way in turnstile to set particular variables (such as `XDG_CONFIG_HOME`), useful for certain user services?
This is on Void Linux, used in conjunction with dinit.
Right now I use
```
$ cat .config/dinit.d/env-var-xdg 
XDG_CONFIG_HOME=/home/dkwo/.config
```
Also, when dinit is launched by turnstiled, is there a way to pass it arguments like `--console-level` or `-q`?

**Comment by dkwo** [comment]
perhaps this has more to do with dinit rather than turnstile.

**Comment by q66** [comment]
yes this should be done separately and has nothing to do with turnstile (you can use `dinitctl setenv` to set anything in the service activation env)
