### ISSUE TITLE
org.freedesktop.login1 dbus interface

### ISSUE THREAD

**Issue by zackattackz** [chimera-linux/turnstile#18]
I wanted to ask if there is an eventual goal for turnstile to support the org.freedesktop.login1 dbus interface. From my understanding, this interface is required by certain applications for managing session/seat related things. 

The login1 interface has endpoints for session AND seat management, but turnstile is only focused on sessions, and not seats. So then it would make sense that turnstile would not implement the seat related functions, and your seat manager (likely seatd) would need to implement those functions to have a fully compliant login1 interface. 

One of the eventual goals stated by turnstile is "a library to examine session information". Would it then be possible to utilize this library to implement the session related functions of login1?

I just wanted to gather thoughts on this. My knowledge of the whole seat/session ecosystem is pretty limited but I am interested to help out in some way!

**Comment by q66** [comment]
no, it's not a goal, the functionality/abstraction level is not exactly the same

the idea is that applications switch to using libturnstile and then they'll be able to interact with both turnstile and logind through backends

**Comment by zackattackz** [comment]
Makes sense, thank you for the quick answer!
