### ISSUE TITLE
question

### ISSUE THREAD

**Issue by dkwo** [chimera-linux/turnstile#9]
"Its ultimate goal is to provide a fully featured replacement for the logind component of systemd": does this imply that, in the future, it will not be necessary to be a member of audio/video groups to run pipewire? I believe seatd does not deal with acl on audio/video, while this is taken care (in some way) by logind, and wanted ot know whether turnstile plans to address this. See also the discussion https://todo.sr.ht/~kennylevinsen/seatd/16

**Comment by q66** [comment]
no, turnstile will not deal with anything that has to do with device access, it's purely a session tracking framework, this should be handled with a separate daemon (perhaps one that uses turnstile's future api to track the sessions)
